# Site settings
title: HDC Lab
email: hdc@email.arizona.edu
description: > # this means to ignore newlines until "baseurl:"
  The HDC Lab studies how Humans, Data, and Computers interact.
  We research novel data analysis and visualization methods, 
  and build software around human minds, rather the other way
  around. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hdc.cs.arizona.edu/" # the base hostname & protocol for your site
twitter_username: hdc_arizona
github_username:  hdc-arizona

collections:
 - students
 - faculty
 - alumni

# Build settings
markdown: kramdown
highlighter: rouge

exclude: ['extras', 'LICENSE', 'README.md']

